### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by Kai-web** [1006008051/vitepress-demoblock#2]
![image](https://user-images.githubusercontent.com/59676989/195984501-bc49f00c-5fa3-4193-81c4-73e0b6e9e6fa.png)

**Comment by 1006008051** [comment]
不支持commonjs模式，请使用esm模式。在 package.json中添加  "type": "module"

**Comment by 1006008051** [comment]
不支持commonjs模式，请使用esm模式。先在 package.json中添加 "type": "module"，并将require导入，代为import的形式。
